### ISSUE TITLE
Incomplete LICENSE file

### ISSUE THREAD

**Issue by puhitaku** [tvlad1234/Pico-10BASE-T-Library#1]
Thanks for packaging into a library.
Your LICENSE file does not contain the original author and is considered non-healthy (in other words, it's violating the license agreement at present because the MIT License says `The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`)

I'll create a pull request to fix this issue. Please consider merging this so I can use your library in my project. Thank you!

**Comment by tvlad1234** [comment]
Thank you for bringing this up! I forgot to mention the author in the LICENSE file, only in the Readme. I merged your PR into my repository, so it should be fixed.
